# Generated by Django 4.2.16 on 2024-10-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unsuccessful_login_count',
            field=models.IntegerField(default=0),
        ),
    ]
