# Generated by Django 4.2.16 on 2024-10-04 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_unsuccessful_login_count'),
        ('users', '0002_rename_pharmacystaff_cashier_and_more'),
    ]

    operations = [
    ]
