# Generated by Django 4.2.16 on 2024-10-11 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'PharmacyManager'), ('2', 'PharmacyTechnician'), ('3', 'Pharmacist'), ('4', 'Cashier'), ('5', 'Patient'), ('6', 'GeneralUser')], max_length=10),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
