# Generated by Django 4.2.16 on 2024-10-16 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'PharmacyManager'), ('2', 'PharmacyTechnician'), ('3', 'Pharmacist'), ('4', 'Cashier'), ('6', 'GeneralUser')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
