# Generated by Django 4.2.16 on 2024-10-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_user_type_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tablet_count', models.IntegerField(default= 0)),
                ('expiration_date', models.DateField())
            ],
        ),
    ]
