# Generated by Django 4.2.16 on 2024-10-16 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medications',
            name='is_expiring_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medications',
            name='is_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medications',
            name='is_orderable',
            field=models.BooleanField(default=False),
        ),
    ]
