# Generated by Django 4.2.16 on 2024-10-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_csvfile'),
        ('users', '0006_medications'),
    ]

    operations = [
    ]
