# Generated by Django 4.2.16 on 2024-10-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_0006_csvfile_0006_medications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
    ]
