# Generated by Django 4.2.16 on 2024-10-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_medications_is_expired_medications_is_expiring_soon_and_more'),
        ('users', '0008_delete_csvfile'),
        ('users', '0008_merge_0006_medications_0007_patient'),
    ]

    operations = [
    ]
