# Generated by Django 4.2.16 on 2024-10-17 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_patient_date_of_birth'),
        ('users', '0009_merge_20241016_1808'),
    ]

    operations = [
    ]
