# Generated by Django 4.2.16 on 2024-10-18 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20241016_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2006, 10, 22, 19, 50, 56, 28848)),
        ),
    ]
