# Generated by Django 4.2.16 on 2024-11-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='patient',
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Med_Removed', 'Med_Removed'), ('Filled', 'Filled')], max_length=15),
        ),
    ]
