# Generated by Django 4.2.16 on 2024-11-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_activity_medication_remove_activity_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='actor_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action_type',
            field=models.CharField(choices=[('User Login', 'User Login'), ('User Logout', 'User Logout'), ('Medication Removed', 'Medication Removed'), ('Prescription Filled', 'Prescription Filled')], max_length=20),
        ),
    ]
