# Generated by Django 4.2.16 on 2024-11-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_prescription'),
        ('users', '0014_activity_actor_type_alter_activity_action_type'),
        ('users', '0014_medications_price_alter_orderitem_price'),
    ]

    operations = [
    ]
