# Generated by Django 4.2.16 on 2024-11-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_activity_actor_type_alter_activity_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='actor_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
