# Generated by Django 4.2.16 on 2024-11-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_medications_price_alter_orderitem_price'),
        ('users', '0015_merge_20241108_1718'),
    ]

    operations = [
    ]
