# Generated by Django 4.2.16 on 2024-11-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_genericitem_alter_orderitem_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('Picked Up', 'Picked Up'), ('Awaiting Pickup', 'Awaiting Pickup')], max_length=20, null=True),
        ),
    ]
